USE ROLE MYUVIE_DEV;
USE DATABASE MYUVIE_DB;
USE SCHEMA APP;

CREATE IMAGE REPOSITORY IF NOT EXISTS IMAGES;
CREATE STAGE IF NOT EXISTS MODELS ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS MEDIA ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE STAGE IF NOT EXISTS SPECS ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE COMPUTE POOL IF NOT EXISTS MYUVIE_CPU_MODELS
  MIN_NODES = 1 MAX_NODES = 1 INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = FALSE INITIALLY_SUSPENDED = TRUE AUTO_SUSPEND_SECS = 60;

ALTER COMPUTE POOL MYUVIE_CPU_MODELS SET AUTO_RESUME = FALSE AUTO_SUSPEND_SECS = 60;
ALTER COMPUTE POOL MYUVIE_GPU_A10 SET AUTO_RESUME = FALSE AUTO_SUSPEND_SECS = 60;
