SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW IMAGE REPOSITORIES LIKE 'IMAGES' IN SCHEMA MYUVIE_DB.APP;
SHOW STAGES IN SCHEMA MYUVIE_DB.APP;
SHOW COMPUTE POOLS LIKE 'MYUVIE_GPU_A10';
